### ISSUE TITLE
Mod currently broken due to update?

### ISSUE THREAD

**Issue by Carnaxus** [bo0tzz/CustomStartDeck#10]
I'm fully expecting a "yes."  The mod's files all have ".old" added to their extension; is this because the mod is currently broken due to the recent game update?

**Comment by bo0tzz** [comment]
Did you manually disable the mod in thunderstore? It shouldn't do that automatically.

**Comment by Carnaxus** [comment]
I'm an idiot.  I thought I only disabled Promethium.  Never mind!
